name: Generate
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup environment
        run: pip install -r requirements.txt
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Pull v2fly community domain list
        uses: actions/checkout@v3
        with:
          repository: 'v2fly/domain-list-community'
          path: 'domain-list-community'
      - name: Pull Loyalsoldier domain-list-custom
        uses: actions/checkout@v3
        with:
          repository: 'Loyalsoldier/domain-list-custom'
          path: 'tool_geosite'
      - name: Pull Loyalsoldier's geosite tool
        uses: actions/checkout@v3
        with:
          repository: 'Loyalsoldier/domain-list-custom'
          path: 'tool_geosite'
      - name: Install Loyalsoldier's geoip tool
        run: go install -v github.com/Loyalsoldier/geoip@latest
      - name: Generate rules
        run: |
              python generate.py
      - name: Generate Geosite DB
        run: |
              cd tool_geosite
              go run ./ --datapath=../dists/geosite --outputpath=../dists
      - name: Generate GeoIP DB
        run: |
              cat <<EOF
              {
              "input": [
                {
                  "type": "text",
                  "action": "add",
                  "args": {
                    "name": "cn",
                    "uri": "./dists/text/domestic_ip.txt",
                    "onlyIPType": "ipv4"
                  }
                },
                {
                  "type": "text",
                  "action": "add",
                  "args": {
                    "name": "cn",
                    "uri": "./dists/text/domestic_ip6.txt",
                    "onlyIPType": "ipv6"
                  }
                },
                {
                  "type": "clashRuleSetClassical",
                  "action": "add",
                  "args": {
                    "name": "apns",
                    "uri": "./dists/clash-compatible/apns.txt"
                  }
                }
              ],
              "output": [
                {
                  "type": "v2rayGeoIPDat",
                  "action": "output",
                  "args": {
                    "outputName": "geoip.dat",
                    "outputDir": "./dists"
                  }
                }
              ]
              }
              EOF > config.json
              geoip -c config.json
      - name: Remove tmp files
        run: rm -rf dists/geosite
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2e54d1245681bc04eaa33ed5d68bdfa7
          projectName: xkww3n-rules
          directory: ./dists
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
