name: Generate
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup environment
        run: pip install -r requirements.txt
      - name: Pull v2fly community domain list
        uses: actions/checkout@v3
        with:
          repository: 'v2fly/domain-list-community'
          path: 'domain-list-community'
      - name: Generate rules
        run: |
              python generate.py
              python generate_homepage.py
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2e54d1245681bc04eaa33ed5d68bdfa7
          projectName: xkww3n-rules
          directory: ./dists
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
