name: Generate
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install requests
          mkdir dists
          mkdir dists/clash
          mkdir dists/surge
      - name: Pull v2fly community domain list
        uses: actions/checkout@v3
        with:
          repository: 'v2fly/domain-list-community'
          path: 'domain-list-community'
      - name: Generate rules
        run: python generate.py
      - name: Copy custom rules to dists directories
        run: |
          cp custom/clash/* dists/clash/
          cp custom/surge/* dists/surge/
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: dists
          fqdn: rules.xkww3n.cyou
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}